### ISSUE TITLE
Color blind players cannot see much of the in-game UI

### ISSUE THREAD

**Issue by janxious** [saltyhotdog/BattletechIssueTracker#11]
**Describe the problem**

There are a number of combinations of planet type and time of day combinations that make things like the line of fire cone and line of fire lines/arcs hard or impossible to see for users with color vision deficiency. This also affects indicators for env type like forest, mineral field, etc. 

As an example, this is roughly what the vanilla indirect firing arc looks like to a normal user:
<img src="https://user-images.githubusercontent.com/50124/40902621-9c2e3e4e-67a2-11e8-8e78-c84f416efdfe.png" width="300px" />

And then one with full color blindness:
<img src="https://user-images.githubusercontent.com/50124/40902620-9c14c5c2-67a2-11e8-95c7-43c6f3f4a07b.png" width="300px" />

**Provide an example of the code where the problem occurs**

There's not one specific place, given this is a general problem with the information architecture of the battle UI. But I have chosen to tackle the Line of Fire lines, and that is all in `WeaponRangeIndicators.DrawLine`.

**Provide an example of your proposed solution**

I authored [BTMLColorLOSMod](https://github.com/janxious/BTMLColorLOSMod/blob/master/BTMLColorLOSMod/WeaponRangeIndicators_DrawLine_Patch.cs#L23)'s patch (actually a replacement for `DrawLine`) to improve visibility for myself (not colorblind) and the [most recent release](https://github.com/janxious/BTMLColorLOSMod/releases/tag/v0.6) goes into depth about other changes I made to help visually impaired people.

I believe there is probably room for some in-game help for people similar to how WoW does it (https://www.dailydot.com/parsec/world-of-warcraft-colorblind-accessibility-options/). At the very least the ability to change the defaults to something else mid-fight would be a huge win.

**Leave any additional comments here**

There is a good discussion in this reddit post from a couple users talking about how the game worked for them and some of the issues they ran into: https://www.reddit.com/r/Battletechgame/comments/8mz7cq/master_list_bugs_qols/dzro4lg/

**Comment by caardappel-hbs** [comment]
This is fantastic feedback and has been forwarded to the UX team for assessment.

**Comment by janxious** [comment]
Sounds good. Thanks for forwarding it on!

**Comment by Morphyum** [comment]
closeing for now since its forwarded to the right people.
