### ISSUE TITLE
Resizing Starmap

### ISSUE THREAD

**Issue by Morphyum** [saltyhotdog/BattletechIssueTracker#4]
**Describe the location in the code your question is about**
StarmapScreen.RenderStarmap() or where else the actual starmap gets rendered.

**What is the question you have about this code?**
I want to resize the actual starmap, so that you have to scroll more and the systems are more spread out.
What are the variables, that i have to look for?

**Leave any additional comments here**
I tried to change _Size and _AspectRatio already and both didn't achieve anything.

**Comment by caardappel-hbs** [comment]
StarmapScreen has two private variables, width and height, that determine the size of the RenderTexture. Try manipulating those as well.

**Comment by Morphyum** [comment]
I tried those too but they seem to have absolutely no effects :-/

**Comment by caardappel-hbs** [comment]
_starRT should also be set to null to force the recalculation.

**Comment by Morphyum** [comment]
Sadly that also did have no effect :-/

**Comment by Morphyum** [comment]
```
private void RefreshStarmap()
		{
			this.height = 4000;
			this._starRT = null;
			if (this.starmap == null)
			{
				return;
			}
			Vector3 localScale = base.transform.localScale;
			float aspectRatio = 1f;
			this.RenderStarmap(this.starmap, this.screenMaterial, this.starRT, this.size, this.starTex, aspectRatio);
		}
```

**Comment by Morphyum** [comment]
We managed to do it, so closeing this
