### ISSUE TITLE
Border Rendering

### ISSUE THREAD

**Issue by Morphyum** [saltyhotdog/BattletechIssueTracker#5]
**Describe the location in the code your question is about**
StarmapBorders.RenderBorders()

**What is the question you have about this code?**
When i add a lot of stars(+2000), the Borders don't get rendered correctly anymore. Also some factions, that are not on the map originally don't render the bold borders between them.

Is there another place than this method that is part of the border generation, or is the algorithm for it just overloaded with so many stars?

**Comment by caardappel-hbs** [comment]
I've forwarded this to our tech art team for further assessment. Full disclosure, it's fairly low priority for us at this time.

**Comment by Morphyum** [comment]
ofcourse no worries, i disabled the borders for my map, with all those colors it's still good to see.

**Comment by caardappel-hbs** [comment]
The shader is hardcoded to only consider 170 star positions when performing calculations. This was due to a rendering limitation of OpenGL on Mac. We are considering increasing this limit for a future update.

**Comment by Morphyum** [comment]
Ah good that answers my question fully, closeing this ticket, Thanks :)
